### ISSUE TITLE
Undefined property: Hirak\Prestissimo\CurlRemoteFilesystem::$lastHeaders

### ISSUE THREAD

**Issue by bazo** [hirak/prestissimo#10]
[ErrorException]
Undefined property: Hirak\Prestissimo\CurlRemoteFilesystem::$lastHeaders

when running composer update

composer version fff5074bbf5697a907b2832902d4219801b90bc5

**Comment by naroga** [comment]
I too am going through this.

**Comment by adamlc** [comment]
I also got this, it appeared to happen when pulling from Toran Proxy, which is behind HTTP auth, not sure if this is related, but it might help :smile:

**Comment by naroga** [comment]
@adamic, I too was pulling from Toran.

**Comment by jhoff** [comment]
+1, also using Toran.

**Comment by jhoff** [comment]
As a quick fix, you can add the following to CurlRemoteFilesystem.php:

protected $lastHeaders = [];

This allows it to work behind Toran.

I would submit a pull request, but I don't fully understand the implications of adding that line.

**Comment by jhoff** [comment]
Also, unfortunately, this package doesn't seem to improve the performance of Toran at all for me.

**Comment by brunoric** [comment]
This issue is related with the #16 and pull request #9 fixes it.

**Comment by hirak** [comment]
I merged #19. Thank you @brunoric !

@bazo @jhoff 
Could you try `dev-master`?

```bash
# (setup)
$ composer config -g repositories.presto git 'git://github.com/hirak/prestissimo.git'
$ composer global remove hirak/prestissimo
$ composer global require 'hirak/prestissimo:*@dev-master'
```

```bash
# (clean & re-install stable)
$ composer config -g --unset repositories.presto
$ composer global remove hirak/prestissimo
$ composer global require hirak/prestissimo
```

**Comment by jhoff** [comment]
```
-bash-4.1$ composer global require 'hirak/prestissimo:dev-master'
Changed current directory to /home/www/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)             
  - Installing hirak/prestissimo (dev-master af1a9d4)
    Cloning af1a9d44a1fc406de195943c8347d83ae11dbc39

Writing lock file
Generating autoload files
```

Then I tried a composer update:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Composer\Util\RemoteFilesystem::findHeaderValue() must be of the type array, null given, called in phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php on line 666 and defined in phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:141
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php(666): Composer\Util\RemoteFilesystem->findHeaderValue(NULL, 'last-modified')
#1 phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php(337): Composer\Repository\ComposerRepository->fetchFile('http://lom1-web...', 'provider-tsotoo...', NULL, true)
#2 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php(199): Composer\Repository\ComposerRepository->whatProvides(Object(Composer\DependencyResolver\Pool), 'tsotools-larave...')
#3 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php(188): Composer\DependencyResolver\Pool->computeWhatProvides('tsotool in phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php on line 141

Fatal error: Uncaught TypeError: Argument 1 passed to Composer\Util\RemoteFilesystem::findHeaderValue() must be of the type array, null given, called in phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php on line 666 and defined in phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:141
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php(666): Composer\Util\RemoteFilesystem->findHeaderValue(NULL, 'last-modified')
#1 phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php(337): Composer\Repository\ComposerRepository->fetchFile('http://lom1-web...', 'provider-tsotoo...', NULL, true)
#2 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php(199): Composer\Repository\ComposerRepository->whatProvides(Object(Composer\DependencyResolver\Pool), 'tsotools-larave...')
#3 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php(188): Composer\DependencyResolver\Pool->computeWhatProvides('tsotool in phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php on line 141
```

**Comment by hirak** [comment]
@jhoff Oh, sorry. Thank you for testing.
I'll rewrite and fix it soon.
