### ISSUE TITLE
Cannot install with Magento 2

### ISSUE THREAD

**Issue by joshuaadickerson** [hirak/prestissimo#160]
I'm not sure where the issue is - with Magento's massive changes to installing with Composer or with Prestissimo - but I get the following error when I composer creates the autoload files.

```Source class "\Hirak\Prestissimo\ParallelizedComposerInterface" for "Hirak\Prestissimo\ParallelizedComposerRepository" generation does not exist.#0 /var/www/html/vendor/magento/framework/Code/Generator.php(112): Magento\Framework\Code\Generator->tryToLoadSourceClass('Hirak\\Prestissi...', Object(Magento\Framework\ObjectManager\Code\Generator\Repository))
#1 /var/www/html/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Hirak\\Prestissi...')
#2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Hirak\\Prestissi...')
#3 [internal function]: spl_autoload_call('Hirak\\Prestissi...')
#4 /var/www/html/var/composer_home/vendor/hirak/prestissimo/src/Plugin.php(63): class_exists('Hirak\\Prestissi...')
#5 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(236): Hirak\Prestissimo\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\BufferIO))
#6 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Hirak\Prestissimo\Plugin))
#7 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#8 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(79): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#9 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(377): Composer\Plugin\PluginManager->loadInstalledPlugins()
#10 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(569): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), Array, false)
#11 /var/www/html/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/var/www/html/c...')
#12 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(362): Magento\Framework\Composer\ComposerFactory->create()
#13 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(375): Magento\Framework\Composer\ComposerInformation->getComposer()
#14 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(242): Magento\Framework\Composer\ComposerInformation->getLocker()
#15 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(104): Magento\Framework\Composer\ComposerInformation->getSystemPackages()
#16 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(65): Magento\Framework\App\ProductMetadata->getSystemPackageVersion()
#17 /var/www/html/vendor/magento/framework/Console/Cli.php(91): Magento\Framework\App\ProductMetadata->getVersion()
#18 /var/www/html/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#19 {main}```

**Comment by kkrieger85** [comment]
@joshuaadickerson I think you have to install prestissimo globally **before** you install M2

you have composer on your server? 
Then install prestissimo: `$ composer global require hirak/prestissimo`

After that, your M2 Installation will run faster.

**Comment by ktomk** [comment]
If you install Prestissimo globally and remove it from your Magento 2 project, it should work. That is also the suggested mode of operation, according to the backtrace, it was installed inside the Magento 2 project which is not how Prestissimo works.

It btw. is constantly integrated with Magento 2 in the [agerun project's Travis build:

* Example: https://travis-ci.org/netz98/n98-magerun2/jobs/323320240#L526-L535

**Comment by drdouglasghd** [comment]
I have successfully used with Magento 2 by following the instructions to install it globally first. 
Note: Pay attention to the user that you globally install it for. If you are building in a deployment environment, the user should be your web user, or whatever user you are installing/configuring Magento with.
